# Generated by Django 4.2.16 on 2024-10-10 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('h1_count', models.IntegerField(default=0)),
                ('h2_count', models.IntegerField(default=0)),
                ('h3_count', models.IntegerField(default=0)),
                ('links', models.JSONField(default=list)),
                ('created_at',
                 models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
