version: '3'

services:
  postgres_db:
    container_name: postgres_db
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env
  
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    env_file: .env
    links:
      - postgres_db